ALTER TABLE Contacts MODIFY Name varchar(255) NULL DEFAULT '';
ALTER TABLE Contacts MODIFY Email varchar(255) NULL DEFAULT '';
ALTER TABLE Contacts MODIFY Mobile varchar(255) NULL DEFAULT '';
ALTER TABLE Contacts MODIFY Address varchar(255) NULL DEFAULT '';
ALTER TABLE Notes MODIFY Note text NULL;