stages:
  - test
  - build

Test:
  stage: test
  image: node:10.15.3
  services:
    - mysql:5.6
  variables:
    MYSQL_DATABASE: arise4c_test
    MYSQL_ROOT_PASSWORD: root
    NODE_ENV: test
    DB_MIGRATE_ENV: test
  script:
    - npm install
    - npm run test
  only:
    - master

Build&Push Docker Image:
  stage: build
  image: docker
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$(cat package.json | grep version | head -1 | awk -F ":" '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]') .
    - docker push $CI_REGISTRY_IMAGE:$(cat package.json | grep version | head -1 | awk -F ":" '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
  only:
    - master
